name: Build MQ
on:
  push:
    tags:
      - v0.*.*
jobs:
  integrity_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3
          python -m venv .venv
          source ./.venv/bin/activate
          pip install -r ./scripts/requirements.txt
      - name: Test
        run: |
          echo 'toutou' > ./text1.txt
          echo 'salut' > ./text2.txt
          zip /tmp/text.zip ./text1.txt ./text2.txt
          ls -l /tmp
          cd /tmp
          unzip text.zip

  linux_build:
    runs-on: ubuntu-latest
    needs: integrity_check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            python3 \
            shellcheck \
            libsdl2-dev \
            libsdl2-image-dev \
            libopengl-dev \
            libswscale-dev \
            libavutil-dev \
            libavformat-dev \
            libavcodec-dev
          python -m venv .venv
          source ./.venv/bin/activate
          pip install -r ./scripts/requirements.txt
      - name: Setup env
        run: |
          tag_name="$(echo ${{ github.ref_name }})"
          version="$(echo $tag_name | grep -Eo '[0-9]+.[0-9]+.[0-9]+$')"
          echo "version=${version}" >> $GITHUB_ENV
      - name: Build all
        run: |
          source ./.venv/bin/activate
          ./.ci/check-integrity.sh "${{ env.version }}"
          ./.ci/build-linux.sh "${{ env.version }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: mq-linux
          path: ./build/mq-linux*
          if-no-files-found: error
          retention-days: 1

      # ./.ci/gen-changelog.sh "${{ env.version }}"
      # - name: 'Create the release'
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     name: '${{ env.version }} (${{ env.date_info }})'
      #     body_path: './build/changelog.md'
      #     files: ./build/mq-*
      #     prerelease: true
      #     make_latest: true

  # macos_build:
  #   runs-on: macos-14
  #   env:
  #     HOMEBREW_NO_AUTO_UPDATE: 1
  #     HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
  #     HOMEBREW_NO_ENV_HINTS: 1
  #     HOMEBREW_NO_INSTALL_CLEANUP: 1
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v6
  #     - name: Setup dependencies
  #       run: |
  #         brew install -f --quiet \
  #           python \
  #           shellcheck \
  #           sdl2 sdl2_image \
  #           glfw3 glew \
  #           ffmpeg
  #         python -m venv .venv
  #         source ./.venv/bin/activate
  #         pip install -r ./scripts/requirements.txt
  #     - name: Setup Env
  #       run: |
  #         tag_name="$(echo ${{ github.ref_name }})"
  #         version="$(echo $tag_name | grep -Eo '[0-9]+.[0-9]+.[0-9]+$')"
  #         echo "version=${version}" >> $GITHUB_ENV
  #     - name: Build all
  #       run: |
  #         source ./.venv/bin/activate
  #         ./.ci/check-integrity.sh "${{ env.version }}"
  #         ./.ci/build-macos.sh "${{ env.version }}"

  generate_release:
    runs-on: ubuntu-latest
    needs:
      - linux_build
      # - macos_build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Env
        run: |
          tag_name="$(echo ${{ github.ref_name }})"
          version="$(echo $tag_name | grep -Eo '[0-9]+.[0-9]+.[0-9]+$')"
          echo "version=${version}" >> $GITHUB_ENV
          echo "date_info=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Generate changelog information
        run: |
          sudo apt-get update
          sudo apt-get install -y python3
          python -m venv .venv
          source ./.venv/bin/activate
          pip install -r ./scripts/requirements.txt
          source ./.venv/bin/activate
          ./.ci/gen-changelog.sh "${{ env.version }}"
      - name: Fetch linux artifacts
        uses: actions/download-artifact@v6
        with:
          name: mq-linux
          path: ./build/
      - name: 'Create the release'
        uses: softprops/action-gh-release@v2
        with:
          name: '${{ env.version }} (${{ env.date_info }})'
          body_path: './build/changelog.md'
          files: ./build/mq-*
          prerelease: true
          make_latest: true
