name: Build MQ
on:
  release:
    types: [created]

jobs:
  integrity_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Check integrity
        uses: ./.github/actions/mq-env-exec
        with:
          dependencies: |
            python3
            shellcheck
          commands: |
            ./.ci/check-integrity.sh {MQ_VER}

  linux_build:
    runs-on: ubuntu-latest
    needs: integrity_check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Build all (linux)
        uses: ./.github/actions/mq-env-exec
        with:
          dependencies: |
            cmake
            python3
            libsdl2-dev
            libopengl-dev
            nasm
          commands: |
            ./.ci/build-linux.sh {MQ_VER}
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: mq-linux
          path: ./build/mq-linux*
          if-no-files-found: error
          retention-days: 1

  web_build:
    runs-on: ubuntu-latest
    needs: integrity_check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Build all (Emscripten)
        uses: ./.github/actions/mq-env-exec
        with:
          dependencies: |
            cmake
            python3
            nasm
          commands: |
            ./.ci/build-emscripten.sh {MQ_VER}
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: mq-web
          path: ./build/mq-web*
          if-no-files-found: error
          retention-days: 1

  update_release:
    runs-on: ubuntu-latest
    needs:
      - linux_build
      - web_build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup env
        id: setup-env
        uses: ./.github/actions/mq-env-exec
      - name: Fetch artifacts
        uses: actions/download-artifact@v6
        with:
          path: ./build/
      - name: 'Create the release'
        uses: softprops/action-gh-release@v2
        with:
          name: '${{ env.mq_version }} (${{ env.mq_dateinfo }})'
          files: |
            ./build/mq-linux/*
            ./build/mq-web/*
          make_latest: true
        env:
          mq_version: ${{ steps.setup-env.outputs.mq-version }}
          mq_dateinfo: ${{ steps.setup-env.outputs.mq-dateinfo }}
